### ISSUE TITLE
Why is "messsaging" written with 3 s?

### ISSUE THREAD

**Issue by jakobjw** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#121]
Hi,

is there any particular reason why "messsaging" is written with 3 s in the artifact id?

- https://quarkus.io/extensions/io.quarkiverse.reactivemessaging.nats-jetstream/quarkus-reactive-messsaging-nats-jetstream/
- `quarkus-reactive-messsaging-nats-jetstream`

Br Jakob

**Comment by kjeldpaw** [comment]
no, that's a typo. It will be fixed soon
