### ISSUE TITLE
Feasability to adapt the extension to a NATS server with JetStream disabled

### ISSUE THREAD

**Issue by adrian-ramirezc** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#131]
Hello @kjeldpaw,

Thanks for developing this quarkus extension.

I wonder how feasible is to adapt the connector to work with a NATS server which jetstream option is disabled. My application does not require messages to be stored. 

Thanks for your time,
Adrian

**Comment by kjeldpaw** [comment]
Hi @adrian-ramirezc I have no plans for that. But it's possible to configure JetStream to only store messages in memory
