### ISSUE TITLE
Dead guide link in extension metadata

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#15]
Hi, I notice that https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream/blob/main/runtime/src/main/resources/META-INF/quarkus-extension.yaml points to https://quarkiverse.github.io/quarkiverse-docs/reactive-messsaging-nats-jetstream/dev/ as a docs link, but that page doesn't exist. I suggest either removing the docs link temporarily (and, ideally, doing a re-release) or following the instructions at https://hub.quarkiverse.io/#documenting-your-extension to get the docs published. Either is a good option!

**Comment by kjeldpaw** [comment]
Hi @holly-cummins I will fix the link ASAP

**Comment by holly-cummins** [comment]
Super!
