### ISSUE TITLE
health readiness check is not recovering

### ISSUE THREAD

**Issue by Saphri** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#201]
Initially health ready reports everything ok as expected

`$ curl localhost:8080/q/health/ready

{
    "status": "UP",
    "checks": [
       {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "UP",
            "data": {
                "data": "[OK] - Connection established",
                "data2": "[OK] - Connection established"
            }
        }
    ]
}`

now I restart the NATS docker image (same port mappings ect)

Service sees that it lost connection:
`2024-10-08 21:45:35,073 ERROR [io.qua.rea.mes.nat.jet.cli.con.DefaultErrorListener] (pool-14-thread-1) Caught exception connecting to [nats://localhost:4222] with message: Read channel closed.
2024-10-08 21:45:35,073 ERROR [io.qua.rea.mes.nat.jet.cli.con.DefaultErrorListener] (pool-16-thread-1) Caught exception connecting to [nats://localhost:4222] with message: Read channel closed.
2024-10-08 21:45:35,075 INFO  [io.qua.rea.mes.nat.jet.cli.Connection] (pool-16-thread-1) Event: Disconnected, message: Connection disconnected
2024-10-08 21:45:35,075 INFO  [io.qua.rea.mes.nat.jet.cli.Connection] (pool-14-thread-1) Event: Disconnected, message: Connection disconnected
2024-10-08 21:45:35,075 INFO  [io.qua.rea.mes.nat.jet.cli.Connection] (pool-16-thread-1) Event: Closed, message: Connection closed
2024-10-08 21:45:35,076 INFO  [io.qua.rea.mes.nat.jet.cli.Connection] (pool-14-thread-1) Event: Closed, message: Connection closed`

So far everything seems ok.. but the service keeps reporting readiness as DOWN.. this was 10+ mins after NATS was up and running again
`$ curl localhost:8080/q/health/ready

{
    "status": "DOWN",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "data": "[KO] - Connection closed",
                "data2": "[OK] - Connection closed"
            }
        }
    ]
}`

I would expect this to be back at UP status

**Comment by Saphri** [comment]
Adding more data... I did a manual curl against the service just for fun... this would not happen as K8S would have stopped traffic
One connection 'data2' came back, but the other 'data' stayed down
`2024-10-08 21:59:28,291 INFO  [io.qua.rea.mes.nat.jet.cli.Connection] (pool-18-thread-1) Event: Connected, message: Connection established
`

`$ curl localhost:8080/q/health/ready
{
    "status": "DOWN",
    "checks": [
        {
            "name": "SmallRye Reactive Messaging - readiness check",
            "status": "DOWN",
            "data": {
                "data": "[KO] - Connection closed",
                "data2": "[OK] - Connection established"
            }
        }
    ]
}`

data is incoming, data2 is outgoing

So still a pod would be rejecting requests in this state

**Comment by Saphri** [comment]
Just tested the 3.15.6 release. No change so far

**Comment by Saphri** [comment]
Found the root of the issue.. I think...

In ConnectionOptionsFactory maxReconnects is hardcoded to 0
This turns off reconnects.. there is no way to configure the reconnect options via the config

https://docs.nats.io/using-nats/developer/connecting/reconnect

**Comment by kjeldpaw** [comment]
I have updated the connection configuration to also include attempts and backoff. I have made a fix to ReaderSubscription so it fails if the connection is lost or the subscription becomes inactive.

**Comment by Saphri** [comment]
And I can confirm that the issue seems to be gone now 😄
