### ISSUE TITLE
Add stream configuration properties

### ISSUE THREAD

**Issue by s4iko** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#213]
Hello,

some stream properties are not available to configure a stream, such as "max-msgs", it may be convenient to add them to avoid a manual operations after the automatic stream creation.

Moreover, some properties are available at a global level (under quarkus.messaging.nats.nats.jet-stream) but are streams' properties in Nats, such as "replicas", "storage-type", ... it would be more flexible if those properties were at the stream level (under quarkus.messaging.nats.nats.jet-stream.streams[i]).
The global properties may be kept for simple cases and backward compatibility.

Thanks for your answer and your awesome work.

Best regards.

**Comment by kjeldpaw** [comment]
Hi, sorry I forgot to update the doc. The properties are already moved to streams config

**Comment by kjeldpaw** [comment]
But yes some configuration properties are missing. I'll look into it

**Comment by kjeldpaw** [comment]
I have added configuration properties to the latest release (3.15.9)
