### ISSUE TITLE
Async publish

### ISSUE THREAD

**Issue by s4iko** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#214]
Hello,

this one is not really an issue, it's more a question or a proposal.

Nats jetstream is not able to receive messages in bulk. The recommended solution by Nats developer is to use asynchronous publish in this case.

Would it be possible to have 2 modes, synchronized (the existing one and default) and synchronized to publish to a stream. We may imagine an async boolean property (or a mode property with sync/async values) on the stream to choose the mode ?

**Comment by kjeldpaw** [comment]
Hi @s4iko have you tried the publish subscriber? or are you looking for something else?

**Comment by s4iko** [comment]
Hi @kjeldpaw, i'm not sure what do you mean exactly by publish subscriber, so I'll just describe how I use the extension.
I use it to consume and publish messages using SmallRye Reactive Messaging, most of the time using @incoming() @outgoing() annotation, the pattern is: get messages from a stream => do  some work => send new messages to another stream.
The incoming part is configured in pull mode (batch of 100 messages).
The outgoing part cannot be configured (or I missed something), so the messages are sent 1 by 1.

In the implementation of the Nats Jetstream extension I saw that the method JetStream.publish() is used to publish messages to Nats Jetstream in an synchronized way. A method JetStream.publishAsync() exists which allow to send messages in an aynchronized way.

This publishAsync() method is a way to increase the throughput significantly and is often given as a solution/workaround for those who want to publish messages in bulk (using nats bench also show that it is much more efficient).
I think this async method may fit well in a reactive micro-service and may improve the performances but there are probably  drawbacks that I don't see actually and it may not be a so good idea...
If it is possible, a configuration option may be added on the outgoing object to select if the message is sent using sync or async way.

What do you think ?

**Comment by kjeldpaw** [comment]
Sorry I misunderstood your issue. I think it's a good idea to use the async publish method. I have created a new release where it's implemented

**Comment by s4iko** [comment]
I have no issue. In fact, it was more a question/suggestion about using async publish to improve throughput and I get my answer:

> I think it's a good idea to use the async publish method. I have created a new release where it's implemented

Awesome ! Thanks :)
