### ISSUE TITLE
Stream auto configuration : the getter for maximumMessages return the value of maximumConsumers

### ISSUE THREAD

**Issue by s4iko** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#227]
Hello,

Everything is in the title ;)

https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream/blob/6532e1d914375f11e3a5f1cd3858b898d0e2962f/runtime/src/main/java/io/quarkiverse/reactive/messaging/nats/jetstream/client/configuration/DefaultStreamConfiguration.java#L84

Thanks again for the great work !

**Comment by kjeldpaw** [comment]
Well spotted :) It''s fixed
