### ISSUE TITLE
Support for Pull based Subscribers

### ISSUE THREAD

**Issue by darren-bell-optiva** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#24]
Hi
The new component looks great and will be an excellent contribution to the Quarkus arsenal.
If I have inspected the code correctly it currently supports the "Push" subscription type only. Are there any plans to add the "Pull" option also? Or indeed, any guidance as to how it could be added.
Many Thanks

**Comment by kjeldpaw** [comment]
Hi @darren-bell-optiva support for pull is soon ready. I'm preparing a release 1.2.0 where pull is supported.
