### ISSUE TITLE
How to replace JetStreamOutgoingMessageMetadata?

### ISSUE THREAD

**Issue by adutra** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#246]
#243 deleted the `JetStreamOutgoingMessageMetadata` class and there seems to be no easy replacement.

I used to use it to pass a subtopic when sending messages to nats:

```java
  @Override
  protected org.eclipse.microprofile.reactive.messaging.Message<T> createMessage(Event upstreamEvent, T messagePayload) {
    Map<String, List<String>> headers = new HashMap<>();
    createHeaders(upstreamEvent, (name, value) -> headers.put(name, List.of(value)));
    JetStreamOutgoingMessageMetadata metadata =
        JetStreamOutgoingMessageMetadata.of(
            upstreamEvent.getIdAsText(), headers, subtopic(upstreamEvent));
    return org.eclipse.microprofile.reactive.messaging.Message.of(messagePayload, org.eclipse.microprofile.reactive.messaging.Metadata.of(metadata));
  }
```

How can I achieve the equivalent now? I cannot upgrade to 3.17.5 because of that.

**Comment by kjeldpaw** [comment]
Sorry please have a look at 3.17.6 where I have reimplemented the support for subtopics. JetStreamOutgoingMessageMetadata is renamed to SubscribeMessageMetadata. Sorry for the inconvenience
