### ISSUE TITLE
Dead docs link in superseded extension metadata

### ISSUE THREAD

**Issue by holly-cummins** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#39]
This is a bit complicated, and I'm not sure what the optimum fix is. 

It looks like two jetstream extensions have been published, one with the `io.quarkiverse` extension (https://quarkus.io/extensions/io.quarkiverse/quarkus-reactive-messsaging-nats-jetstream/) and one with a group id that include nats jetstream (https://quarkus.io/extensions/io.quarkiverse.reactivemessaging.nats-jetstream/quarkus-reactive-messsaging-nats-jetstream/). 

The docs link in the older version of the extension is dead. It's only a little issue, but we try not to have dead links. I can see the following solutions:

- Mark the older extension as 'deprecated' (by adding that to its status). We silently drop dead guide links on deprecated extensions, because who would want to maintain them? The deprecated status seems technically correct, but needs a rerelease of the 'old' extension, which is annoying, because it's supposed to be old. I think you'd need to make a maintenance branch that forks off from before the group id change and then release from that branch.
- Just update the guide link in the old extension. This also needs a rerelease of old code. 
- Sneakily delete the old extension from the registry. @gastaldi would be able to do this, I think. It saves this team doing a re-release, and makes the extension with the incorrect group id go away completely. However, it's re-writing history, which isn't ideal, and it could have some unintended consequences.
- Patch the old extension in the registry with the new link. I think @gastaldi can do this too, and it saves the re-release with fewer unintended consequences.
- Holly adds some exception or hardcoding to handle this case and not publish the dead link on the extensions site. So the registry data stays incorrect, but at least the website is correct. I think this should be a last resort, but it's an option. 

WDYT,  @kjeldpaw and @gastaldi?

**Comment by gastaldi** [comment]
I believe it was never the intention to use the `io.quarkiverse` group ID in that extension (The group ID was changed in subsequent releases: https://github.com/quarkusio/quarkus-extension-catalog/commit/c53afcef1b02e8affd7765515beb37dd9016a15e). 

I'm +1 to sneakily delete it from the registry (FTR I do that using the [REST API](https://registry.quarkus.io/q/swagger-ui/#/Admin/delete_admin_v1_extension))

**Comment by gastaldi** [comment]
Deleted from the registry. Closing this ticket now. Thanks for spotting it @holly-cummins!

**Comment by kjeldpaw** [comment]
It was an accident :( Ozan brought this to my attention quickly and we got it fixed

**Comment by gastaldi** [comment]
@holly-cummins on another topic, in https://quarkus.io/extensions/io.quarkiverse/quarkus-reactive-messsaging-nats-jetstream/ can we make the `A newer version of this extension has been released with the group id io.quarkiverse.reactivemessaging.nats-jetstream` message a link to the newer extension?

**Comment by gastaldi** [comment]
> It was an accident :( Ozan brought this to my attention quickly and we got it fixed

This is something we could have detected in the [pre-release workflow](https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream/blob/main/.github/workflows/pre-release.yml). I'll have a look on how to make it easier for everyone

**Comment by holly-cummins** [comment]
> @holly-cummins on another topic, in https://quarkus.io/extensions/io.quarkiverse/quarkus-reactive-messsaging-nats-jetstream/ can we make the `A newer version of this extension has been released with the group id io.quarkiverse.reactivemessaging.nats-jetstream` message a link to the newer extension?

I was just noticing that today, too. The text at the bottom has the link, but it's natural to try and click on the first message, which is the top. I've raised https://github.com/quarkusio/extensions/issues/635.
