### ISSUE TITLE
Add support for the NATS Key-Value Store

### ISSUE THREAD

**Issue by dharriso** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#86]
Hi 

Ive been looking at the suitability of the Quarkus NATS reactive messaging extension and noticed that the NATS Key-Value store API is not supported.  Is this something you could consider adding?

NATS has a Key-Value store API that is used by the NATS community and would be a great addition for the Quarkus Reactive Message Extension for NATS.

See [here](https://docs.nats.io/nats-concepts/jetstream/key-value-store),   [here](https://natsbyexample.com/examples/kv/intro/java) & [here](https://github.com/nats-io/nats.java/tree/main/src/examples/java/io/nats/examples/jetstream)

Thanks in advance
Declan

**Comment by kjeldpaw** [comment]
Sorry the late answer. It will probably take some time before I can look at implementing a bean to call the key-value store. You are welcome to make a PR if it's urgent:)

**Comment by dharriso** [comment]
no problems just wanted to know if it was on a roadmap.

**Comment by kjeldpaw** [comment]
I have now started implementing support for Key-Value store :) Hopefully I have a release ready next week

**Comment by dharriso** [comment]
Brilliant, thats a great addition IMO. Look forward to see it go live

**Comment by kjeldpaw** [comment]
The latest release contains support for key / value store. I'm still missing to update documentation. But try look at the tests that see how to use it
