### ISSUE TITLE
NATS Quarkus Extension returning a NULL Payload for all messages

### ISSUE THREAD

**Issue by dharriso** [quarkiverse/quarkus-reactive-messaging-nats-jetstream#90]
Hi @kjeldpaw 

Thanks for providing a Quarkus Reactive message connector for NATS. 

Ive been testing with the NATS extension I am see that the Incoming messages from NATS stream called "test" all have a NULL message payload when it reaches the application. However the messages when viewed in NATS all have a payload "help"

Ive stripped down the application to a simple example to upper case in the attached file.

Is there some confguration I am missing here?

I add messages to the stream via the nats cli, e.g. 
"nats pub data --count 10 help"

Thanks in advance
Declan
[quarkus.nats.extension.txt](https://github.com/quarkiverse/quarkus-reactive-messaging-nats-jetstream/files/15047997/quarkus.nats.extension.txt)

**Comment by kjeldpaw** [comment]
It's because when you publish a message from CLI the Java type is missing. The extension reads the Java type from a header or the channel configuration. I can change the behaviour to return the payload as a String or a byte[] if the type is unknown.

**Comment by dharriso** [comment]
Thanks for the response.
The header informs the consumer what the payload to expect here.  I didnt realise that I needed to add a header when I publish to NATS using the CLI to indicate the type of payload.  

Whats the header name I should use here & what is the? I can add it to the cli publish command using the "--header" option. I assume it needs to match the values below.

Perhaps default to byte[]

Are these valid here?
mp.messaging.incoming.source.payload-type=String.class
mp.messaging.incoming.source.payload-type=String
mp.messaging.incoming.source.payload-type=String[]
mp.messaging.incoming.source.payload-type=byte[]
mp.messaging.incoming.source.payload-type=io.nats.client.Message.class

**Comment by kjeldpaw** [comment]
If no header or payload-type not configured the default type is now byte[] from version 1.7.3

**Comment by dharriso** [comment]
Thanks @kjeldpaw plan is for myself or 1 of the team to circle back and look at the NATS extension.
